<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'title' => 'Dashboard',
                'url' => '/dashboard',
                'icon' => '<i class="fa fa-laptop"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-25 12:04:14',
                'updated_at' => '2025-07-26 12:11:05',
            ),
            1 => 
            array (
                'id' => 2,
                'title' => 'Settings',
                'url' => '/settings',
                'icon' => '<i class="fa-regular fa-sun"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 11:28:59',
                'updated_at' => '2025-07-26 12:17:57',
            ),
            2 => 
            array (
                'id' => 3,
                'title' => 'User Management',
                'url' => '/user',
                'icon' => '<i class="fa-regular fa-circle-user"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 11:29:47',
                'updated_at' => '2025-07-26 12:20:15',
            ),
            3 => 
            array (
                'id' => 4,
                'title' => 'Menu Management',
                'url' => '/settings/menu',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 2,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 11:30:09',
                'updated_at' => '2025-07-26 11:30:09',
            ),
            4 => 
            array (
                'id' => 5,
                'title' => 'Role Management',
                'url' => '/settings/roles',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 2,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 11:30:31',
                'updated_at' => '2025-07-26 12:35:27',
            ),
            5 => 
            array (
                'id' => 8,
                'title' => 'General Settings',
                'url' => '/settings/general',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 2,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 12:22:09',
                'updated_at' => '2025-07-26 12:22:09',
            ),
            6 => 
            array (
                'id' => 9,
                'title' => 'User Data',
                'url' => '/users/data',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 3,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 12:22:38',
                'updated_at' => '2025-07-26 16:17:07',
            ),
            7 => 
            array (
                'id' => 10,
                'title' => 'User Activity',
                'url' => '/users/log',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 3,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 12:23:15',
                'updated_at' => '2025-07-26 12:23:15',
            ),
            8 => 
            array (
                'id' => 11,
                'title' => 'Master Data',
                'url' => '/master',
                'icon' => '<i class="fa-solid fa-database"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 12:26:54',
                'updated_at' => '2025-07-26 12:26:54',
            ),
            9 => 
            array (
                'id' => 12,
                'title' => 'Jenjang',
                'url' => '/master/jenjang',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 11,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 12:27:58',
                'updated_at' => '2025-07-26 12:27:58',
            ),
            10 => 
            array (
                'id' => 13,
                'title' => 'Tahun Ajaran',
                'url' => '/master/tahun_ajar',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 11,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:49:34',
                'updated_at' => '2025-07-26 13:49:58',
            ),
            11 => 
            array (
                'id' => 14,
                'title' => 'Jurusan',
                'url' => '/master/jurusan',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 11,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:53:54',
                'updated_at' => '2025-07-26 13:53:54',
            ),
            12 => 
            array (
                'id' => 15,
                'title' => 'Kelas',
                'url' => '/master/kelas',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 11,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:54:24',
                'updated_at' => '2025-07-26 13:54:24',
            ),
            13 => 
            array (
                'id' => 16,
                'title' => 'Rekening Bank',
                'url' => 'master/rekening',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 11,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:01:29',
                'updated_at' => '2025-07-26 14:01:29',
            ),
            14 => 
            array (
                'id' => 17,
                'title' => 'Pendaftaran',
                'url' => '/daftar',
                'icon' => '<i class="fa-solid fa-user-plus"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:21:07',
                'updated_at' => '2025-07-26 14:21:07',
            ),
            15 => 
            array (
                'id' => 18,
                'title' => 'Siswa Baru',
                'url' => '/daftar/baru',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 17,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:21:26',
                'updated_at' => '2025-07-26 14:22:38',
            ),
            16 => 
            array (
                'id' => 19,
                'title' => 'Daftar Ulang',
                'url' => '/daftar/ulang',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 17,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:24:00',
                'updated_at' => '2025-07-26 14:24:00',
            ),
            17 => 
            array (
                'id' => 20,
                'title' => 'Pindah Masuk',
                'url' => '/daftar/pindah_masuk',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 17,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:25:14',
                'updated_at' => '2025-07-26 14:25:14',
            ),
            18 => 
            array (
                'id' => 21,
                'title' => 'Tagihan',
                'url' => '/tagihan',
                'icon' => '<i class="fa-solid fa-receipt"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:26:58',
                'updated_at' => '2025-07-26 14:26:58',
            ),
            19 => 
            array (
                'id' => 22,
                'title' => 'Pembayaran',
                'url' => '/pembayaran',
                'icon' => '<i class="fa-solid fa-money-bill-1-wave"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:27:39',
                'updated_at' => '2025-07-26 14:27:39',
            ),
            20 => 
            array (
                'id' => 23,
                'title' => 'Beasiswa',
                'url' => '/beasiswa',
                'icon' => '<i class="fa-solid fa-percent"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:28:27',
                'updated_at' => '2025-07-26 14:29:16',
            ),
            21 => 
            array (
                'id' => 24,
                'title' => 'Naik Kelas',
                'url' => '/naik',
                'icon' => '<i class="fa-solid fa-angles-up"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:30:12',
                'updated_at' => '2025-07-26 14:41:42',
            ),
            22 => 
            array (
                'id' => 25,
                'title' => 'Laporan',
                'url' => '/laporan',
                'icon' => '<i class="fa-solid fa-list-check"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:31:47',
                'updated_at' => '2025-07-26 14:31:47',
            ),
            23 => 
            array (
                'id' => 26,
                'title' => 'Pemasukan',
                'url' => '/pemasukan',
                'icon' => '<i class="fa-solid fa-file-invoice-dollar"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:32:42',
                'updated_at' => '2025-07-26 14:43:24',
            ),
            24 => 
            array (
                'id' => 27,
                'title' => 'Pengeluaran',
                'url' => '/pengeluaran',
                'icon' => '<i class="fa-solid fa-basket-shopping"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:33:31',
                'updated_at' => '2025-07-26 14:33:31',
            ),
            25 => 
            array (
                'id' => 28,
                'title' => 'Saldo Kas',
                'url' => '/saldo',
                'icon' => '<i class="fa-solid fa-file-invoice"></i>',
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => NULL,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:34:11',
                'updated_at' => '2025-07-26 14:34:11',
            ),
            26 => 
            array (
                'id' => 29,
                'title' => 'Kenaikan Kelas',
                'url' => '/naik/kelas',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 24,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:41:16',
                'updated_at' => '2025-07-26 14:41:16',
            ),
            27 => 
            array (
                'id' => 30,
                'title' => 'Pindah Keluar',
                'url' => '/naik/pindah',
                'icon' => NULL,
                'caret' => 0,
                'is_aktif' => 'on',
                'parent_id' => 24,
                'created_by' => 'admin',
                'updated_by' => 'unknown',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 14:42:14',
                'updated_at' => '2025-07-26 14:42:14',
            ),
        ));
        
        
    }
}