<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RoleAksesMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('role_akses_menus')->delete();
        
        \DB::table('role_akses_menus')->insert(array (
            0 => 
            array (
                'id' => 53,
                'role_id' => 2,
                'menu_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            1 => 
            array (
                'id' => 54,
                'role_id' => 2,
                'menu_id' => 2,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            2 => 
            array (
                'id' => 55,
                'role_id' => 2,
                'menu_id' => 4,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            3 => 
            array (
                'id' => 56,
                'role_id' => 2,
                'menu_id' => 5,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            4 => 
            array (
                'id' => 57,
                'role_id' => 2,
                'menu_id' => 8,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            5 => 
            array (
                'id' => 58,
                'role_id' => 2,
                'menu_id' => 3,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            6 => 
            array (
                'id' => 59,
                'role_id' => 2,
                'menu_id' => 9,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            7 => 
            array (
                'id' => 60,
                'role_id' => 2,
                'menu_id' => 10,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            8 => 
            array (
                'id' => 61,
                'role_id' => 2,
                'menu_id' => 11,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            9 => 
            array (
                'id' => 62,
                'role_id' => 2,
                'menu_id' => 12,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            10 => 
            array (
                'id' => 63,
                'role_id' => 2,
                'menu_id' => 13,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            11 => 
            array (
                'id' => 64,
                'role_id' => 2,
                'menu_id' => 14,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            12 => 
            array (
                'id' => 65,
                'role_id' => 2,
                'menu_id' => 15,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            13 => 
            array (
                'id' => 66,
                'role_id' => 2,
                'menu_id' => 16,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 16:55:25',
                'updated_at' => '2025-07-26 16:55:25',
            ),
            14 => 
            array (
                'id' => 231,
                'role_id' => 1,
                'menu_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            15 => 
            array (
                'id' => 232,
                'role_id' => 1,
                'menu_id' => 2,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            16 => 
            array (
                'id' => 233,
                'role_id' => 1,
                'menu_id' => 4,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            17 => 
            array (
                'id' => 234,
                'role_id' => 1,
                'menu_id' => 5,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            18 => 
            array (
                'id' => 235,
                'role_id' => 1,
                'menu_id' => 8,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            19 => 
            array (
                'id' => 236,
                'role_id' => 1,
                'menu_id' => 3,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            20 => 
            array (
                'id' => 237,
                'role_id' => 1,
                'menu_id' => 9,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            21 => 
            array (
                'id' => 238,
                'role_id' => 1,
                'menu_id' => 10,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            22 => 
            array (
                'id' => 239,
                'role_id' => 1,
                'menu_id' => 11,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            23 => 
            array (
                'id' => 240,
                'role_id' => 1,
                'menu_id' => 12,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            24 => 
            array (
                'id' => 241,
                'role_id' => 1,
                'menu_id' => 13,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            25 => 
            array (
                'id' => 242,
                'role_id' => 1,
                'menu_id' => 14,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            26 => 
            array (
                'id' => 243,
                'role_id' => 1,
                'menu_id' => 15,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            27 => 
            array (
                'id' => 244,
                'role_id' => 1,
                'menu_id' => 16,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            28 => 
            array (
                'id' => 245,
                'role_id' => 1,
                'menu_id' => 17,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            29 => 
            array (
                'id' => 246,
                'role_id' => 1,
                'menu_id' => 18,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            30 => 
            array (
                'id' => 247,
                'role_id' => 1,
                'menu_id' => 19,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            31 => 
            array (
                'id' => 248,
                'role_id' => 1,
                'menu_id' => 20,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            32 => 
            array (
                'id' => 249,
                'role_id' => 1,
                'menu_id' => 21,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            33 => 
            array (
                'id' => 250,
                'role_id' => 1,
                'menu_id' => 22,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            34 => 
            array (
                'id' => 251,
                'role_id' => 1,
                'menu_id' => 23,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            35 => 
            array (
                'id' => 252,
                'role_id' => 1,
                'menu_id' => 24,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            36 => 
            array (
                'id' => 253,
                'role_id' => 1,
                'menu_id' => 29,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            37 => 
            array (
                'id' => 254,
                'role_id' => 1,
                'menu_id' => 30,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            38 => 
            array (
                'id' => 255,
                'role_id' => 1,
                'menu_id' => 25,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:46',
                'updated_at' => '2025-07-26 17:23:46',
            ),
            39 => 
            array (
                'id' => 256,
                'role_id' => 1,
                'menu_id' => 26,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:47',
                'updated_at' => '2025-07-26 17:23:47',
            ),
            40 => 
            array (
                'id' => 257,
                'role_id' => 1,
                'menu_id' => 27,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:47',
                'updated_at' => '2025-07-26 17:23:47',
            ),
            41 => 
            array (
                'id' => 258,
                'role_id' => 1,
                'menu_id' => 28,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'rifqi',
                'updated_by' => 'rifqi',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 17:23:47',
                'updated_at' => '2025-07-26 17:23:47',
            ),
        ));
        
        
    }
}