<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RoleAksesMenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('role_akses_menus')->delete();
        
        \DB::table('role_akses_menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'role_id' => 1,
                'menu_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:28:49',
                'updated_at' => '2025-07-26 13:28:49',
            ),
            1 => 
            array (
                'id' => 2,
                'role_id' => 1,
                'menu_id' => 2,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:28:49',
                'updated_at' => '2025-07-26 13:28:49',
            ),
            2 => 
            array (
                'id' => 3,
                'role_id' => 1,
                'menu_id' => 3,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:28:49',
                'updated_at' => '2025-07-26 13:28:49',
            ),
            3 => 
            array (
                'id' => 4,
                'role_id' => 1,
                'menu_id' => 4,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:28:50',
                'updated_at' => '2025-07-26 13:28:50',
            ),
            4 => 
            array (
                'id' => 5,
                'role_id' => 1,
                'menu_id' => 5,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:28:50',
                'updated_at' => '2025-07-26 13:28:50',
            ),
            5 => 
            array (
                'id' => 6,
                'role_id' => 1,
                'menu_id' => 8,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:28:50',
                'updated_at' => '2025-07-26 13:28:50',
            ),
            6 => 
            array (
                'id' => 7,
                'role_id' => 1,
                'menu_id' => 9,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:28:50',
                'updated_at' => '2025-07-26 13:28:50',
            ),
            7 => 
            array (
                'id' => 8,
                'role_id' => 1,
                'menu_id' => 10,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:28:50',
                'updated_at' => '2025-07-26 13:28:50',
            ),
            8 => 
            array (
                'id' => 9,
                'role_id' => 1,
                'menu_id' => 11,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:28:50',
                'updated_at' => '2025-07-26 13:28:50',
            ),
            9 => 
            array (
                'id' => 10,
                'role_id' => 1,
                'menu_id' => 12,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:28:50',
                'updated_at' => '2025-07-26 13:28:50',
            ),
            10 => 
            array (
                'id' => 15,
                'role_id' => 2,
                'menu_id' => 1,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:29:31',
                'updated_at' => '2025-07-26 13:29:31',
            ),
            11 => 
            array (
                'id' => 16,
                'role_id' => 2,
                'menu_id' => 2,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:29:31',
                'updated_at' => '2025-07-26 13:29:31',
            ),
            12 => 
            array (
                'id' => 17,
                'role_id' => 2,
                'menu_id' => 3,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:29:31',
                'updated_at' => '2025-07-26 13:29:31',
            ),
            13 => 
            array (
                'id' => 18,
                'role_id' => 2,
                'menu_id' => 4,
                'can_create' => 1,
                'can_read' => 1,
                'can_update' => 1,
                'can_delete' => 1,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:29:31',
                'updated_at' => '2025-07-26 13:29:31',
            ),
            14 => 
            array (
                'id' => 19,
                'role_id' => 2,
                'menu_id' => 5,
                'can_create' => 0,
                'can_read' => 1,
                'can_update' => 0,
                'can_delete' => 0,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:29:31',
                'updated_at' => '2025-07-26 13:29:31',
            ),
            15 => 
            array (
                'id' => 20,
                'role_id' => 2,
                'menu_id' => 8,
                'can_create' => 0,
                'can_read' => 1,
                'can_update' => 0,
                'can_delete' => 0,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:29:31',
                'updated_at' => '2025-07-26 13:29:31',
            ),
            16 => 
            array (
                'id' => 21,
                'role_id' => 2,
                'menu_id' => 9,
                'can_create' => 0,
                'can_read' => 1,
                'can_update' => 0,
                'can_delete' => 0,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:29:31',
                'updated_at' => '2025-07-26 13:29:31',
            ),
            17 => 
            array (
                'id' => 22,
                'role_id' => 2,
                'menu_id' => 10,
                'can_create' => 0,
                'can_read' => 1,
                'can_update' => 0,
                'can_delete' => 0,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:29:31',
                'updated_at' => '2025-07-26 13:29:31',
            ),
            18 => 
            array (
                'id' => 23,
                'role_id' => 2,
                'menu_id' => 11,
                'can_create' => 0,
                'can_read' => 1,
                'can_update' => 0,
                'can_delete' => 0,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:29:31',
                'updated_at' => '2025-07-26 13:29:31',
            ),
            19 => 
            array (
                'id' => 24,
                'role_id' => 2,
                'menu_id' => 12,
                'can_create' => 0,
                'can_read' => 1,
                'can_update' => 0,
                'can_delete' => 0,
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'deleted_by' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2025-07-26 13:29:31',
                'updated_at' => '2025-07-26 13:29:31',
            ),
        ));
        
        
    }
}